export const INCREMENT="INCREMENT"
export const DECREMENT="DECREMENT"
export const RESET="RESET"
export const FETCH_PRODUCT_LOADING="FETCH_PRODUCT_LOADING"
export const FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS"
export const FETCH_PRODUCT_FAILED="FETCH_PRODUCT_FAILED"
// src/constants/actionTypes.js
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
